name: Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - uses: actions/setup-node@v4
        with:
          cache: yarn
      - run: yarn install
      - run: yarn test
      - run: yarn build
      - run: yarn deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
